create table zad3 (
    customerNumber int,
    employeeNumber int,
    firstName varchar,
    lastName varchar,
    extension varchar,
    email varchar,
    reportsTo int,
    jobTitle varchar,
    officeCode int,
    city varchar,
    phone varchar,
    addressLine1 varchar,
    addressLine2 varchar,
    state varchar,
    country varchar,
    postalCode varchar,
    territory varchar,
    primary key ( (customerNumber))
);

-- select
--     customerNumber,
--     addressLine1,
--     addressLine2,
--     city,
--     country,
--     email,
--     employeeNumber,
--     extension,
--     firstName,
--     jobTitle,
--     lastName,
--     officeCode,
--     phone,
--     postalCode,
--     reportsTo,
--     state,
--     territory
-- from clientView2;